In [ ]:
#Nate Brune
#3/16/19
#I have not given or received any unauthorized assistance on this assignment 

In [1]:
import numpy as np

In [2]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [3]:
b = np.arange(0,100,10)
print(b)

[ 0 10 20 30 40 50 60 70 80 90]


In [4]:
c = np.linspace(0,10,101,True)
print(c)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [6]:
d = np.random.random((10,10)) 
print(d)

[[0.75558286 0.5561313  0.97080438 0.38808837 0.33307977 0.10714792
  0.84005014 0.63701999 0.17826399 0.77418635]
 [0.92873253 0.59045314 0.05883689 0.48475232 0.23713931 0.43740224
  0.83655561 0.12236937 0.04105144 0.47529485]
 [0.82718219 0.52539577 0.00319102 0.10816741 0.54499803 0.23658329
  0.3978122  0.19459528 0.78926951 0.26990741]
 [0.54744142 0.81187871 0.63414428 0.55197879 0.28462178 0.84181135
  0.84102066 0.15938329 0.31718013 0.9771308 ]
 [0.25791864 0.94144562 0.34434566 0.02811947 0.15374298 0.19222258
  0.32060358 0.59388642 0.18000776 0.42315872]
 [0.60304658 0.54265746 0.74982265 0.55714677 0.58124858 0.99759871
  0.4001041  0.74925024 0.46322565 0.50039627]
 [0.40844401 0.26326851 0.13979633 0.38807444 0.95766161 0.13693671
  0.7551078  0.61985955 0.15182936 0.87172235]
 [0.17087543 0.05706866 0.49015863 0.53236009 0.12585801 0.56067964
  0.11681995 0.15262641 0.21933911 0.34947319]
 [0.83046963 0.84267219 0.75550719 0.27725096 0.36656307 0.46702634
  0.71716074

In [10]:
a = a.reshape(10,10)
print(a)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
a[4,5]
#starts at 0 and counts down to row 4 and column 5 to return the value in that place

45

In [15]:
a[4]
#starts at 0 and counts down to row 4 and returns that row

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
np.sum(d)

46.86488672657251

In [17]:
np.max(a)

99

In [21]:
print(np.transpose(b))

[ 0 10 20 30 40 50 60 70 80 90]


In [22]:
print(a + d)

array([[ 0.75558286,  1.5561313 ,  2.97080438,  3.38808837,  4.33307977,
         5.10714792,  6.84005014,  7.63701999,  8.17826399,  9.77418635],
       [10.92873253, 11.59045314, 12.05883689, 13.48475232, 14.23713931,
        15.43740224, 16.83655561, 17.12236937, 18.04105144, 19.47529485],
       [20.82718219, 21.52539577, 22.00319102, 23.10816741, 24.54499803,
        25.23658329, 26.3978122 , 27.19459528, 28.78926951, 29.26990741],
       [30.54744142, 31.81187871, 32.63414428, 33.55197879, 34.28462178,
        35.84181135, 36.84102066, 37.15938329, 38.31718013, 39.9771308 ],
       [40.25791864, 41.94144562, 42.34434566, 43.02811947, 44.15374298,
        45.19222258, 46.32060358, 47.59388642, 48.18000776, 49.42315872],
       [50.60304658, 51.54265746, 52.74982265, 53.55714677, 54.58124858,
        55.99759871, 56.4001041 , 57.74925024, 58.46322565, 59.50039627],
       [60.40844401, 61.26326851, 62.13979633, 63.38807444, 64.95766161,
        65.13693671, 66.7551078 , 67.61985955

In [23]:
print(a * d)

[[0.00000000e+00 5.56131304e-01 1.94160877e+00 1.16426511e+00
  1.33231908e+00 5.35739609e-01 5.04030082e+00 4.45913996e+00
  1.42611193e+00 6.96767715e+00]
 [9.28732535e+00 6.49498459e+00 7.06042711e-01 6.30178011e+00
  3.31995036e+00 6.56103361e+00 1.33848898e+01 2.08027921e+00
  7.38925920e-01 9.03060217e+00]
 [1.65436437e+01 1.10333111e+01 7.02024316e-02 2.48785033e+00
  1.30799528e+01 5.91458233e+00 1.03431171e+01 5.25407269e+00
  2.20995463e+01 7.82731493e+00]
 [1.64232426e+01 2.51682400e+01 2.02926170e+01 1.82152999e+01
  9.67714067e+00 2.94633971e+01 3.02767437e+01 5.89718190e+00
  1.20528449e+01 3.81081011e+01]
 [1.03167457e+01 3.85992705e+01 1.44625178e+01 1.20913714e+00
  6.76469126e+00 8.65001606e+00 1.47477648e+01 2.79126617e+01
  8.64037230e+00 2.07347773e+01]
 [3.01523288e+01 2.76755304e+01 3.89907778e+01 2.95287788e+01
  3.13874231e+01 5.48679291e+01 2.24058296e+01 4.27072635e+01
  2.68670875e+01 2.95233802e+01]
 [2.45066409e+01 1.60593792e+01 8.66737250e+00 2.44486895e

In [24]:
print(np.dot(a,d))

[[ 25.53378902  21.49648911  20.58305349  17.923028    20.2834117
   19.06018402  20.98956577  25.80438547  14.08568197  22.270866  ]
 [ 86.576179    75.27294645  65.57685712  55.96554498  61.71222747
   60.37283718  75.9815986   74.31190951  44.95568462  75.9535369 ]
 [147.61856897 129.04940379 110.57066075  94.00806195 103.14104325
  101.68549034 130.97363144 122.81943355  75.82568726 129.6362078 ]
 [208.66095895 182.82586113 155.56446438 132.05057893 144.56985903
  142.9981435  185.96566427 171.32695759 106.6956899  183.31887869]
 [269.70334892 236.60231846 200.55826801 170.09309591 185.99867481
  184.31079666 240.9576971  219.83448163 137.56569254 237.00154959]
 [330.74573889 290.3787758  245.55207164 208.13561288 227.42749059
  225.62344981 295.94972994 268.34200567 168.43569519 290.68422048]
 [391.78812887 344.15523314 290.54587527 246.17812986 268.85630636
  266.93610297 350.94176277 316.84952971 199.30569783 344.36689138]
 [452.83051884 397.93169048 335.5396789  284.22064684 31