In [ ]:
#Nate Brune
#3/16/19
#I have not given or received any unauthorized assistance on this assignment 

In [ ]:
'''
From wikipedia:

The universe of the Game of Life is an infinite, two-dimensional orthogonal grid of square cells, 
each of which is in one of two possible states, alive or dead, (or populated and unpopulated, respectively). 
Every cell interacts with its eight neighbours, which are the cells that are horizontally, vertically, 
or diagonally adjacent. At each step in time, the following transitions occur:

Any live cell with fewer than two live neighbours dies, as if by underpopulation.
Any live cell with two or three live neighbours lives on to the next generation.
Any live cell with more than three live neighbours dies, as if by overpopulation.
Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.
'''

In [124]:
import numpy as np

In [125]:
def conway(s,p):
    '''takes in the size and probability a square will be live and returns a starting board for the game'''
    a = np.random.random((s,s))
    b = a + p
    board = b.astype(int)
    return board

In [126]:
def numNeighbors(board,r,c):
    '''takes in a board, row and column and returns the number of neighbors for the value at that index of the board'''
    size = len(board[0])
    left, right = max(0,r-1), min(size+1,r+2)
    upper, lower = max(0,c-1), min(size+1,c+2)
    n = board[left:right, upper:lower]
    if board[r,c] == 1:
        return np.sum(n) - 1
    else:
        return np.sum(n)

In [127]:
def livesOrDies(b,n):
    '''determines whether the number space lives or dies based on the rules of Conways game'''
    if b == 0:
        if n == 3:
            return 1
        else:
            return 0
    else:
        if n < 2 or n > 3:
            return 0
        elif n == 2 or n == 3:
            return 1

In [137]:
def oneRound():
    '''
    brings in global board as global variable and declares new board
    loops through each value in the global board and uses it to declare the new board
    finally sets the global board to the new board
    '''
    global board
    s = len(board[0])
    newBoard = conway(s,0)
    size = len(board[0])
    for r in range(size):
        for c in range(size):
            newBoard[r,c] = livesOrDies(board[r,c],numNeighbors(board,r,c))
    board = newBoard

In [138]:
def printBoard(board):
    '''prints board in clean format'''
    for row in board:
        print(row)

In [140]:
def advance(t):
    '''advances the board by t rounds'''
    for x in range(t):
        oneRound()

In [148]:
board = conway(10, .6)
printBoard(board)

print('') #space to separate boards

advance(1)
printBoard(board)

[1 1 1 0 1 1 1 0 1 1]
[1 1 1 0 1 1 1 1 1 1]
[0 0 1 1 1 1 1 1 0 1]
[0 1 0 1 0 0 1 1 0 1]
[1 1 0 1 0 1 0 1 1 0]
[0 1 1 0 1 0 1 1 0 1]
[1 0 1 1 1 1 1 0 1 1]
[1 0 1 0 1 0 0 1 1 1]
[1 0 0 1 0 0 1 0 0 0]
[0 1 1 1 0 0 0 0 1 1]

[1 0 1 0 1 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 1]
[1 1 0 0 0 0 0 0 0 1]
[1 0 0 1 0 1 0 0 0 1]
[0 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 0]
[1 0 1 0 0 0 0 0 0 1]
[1 0 0 0 1 0 0 0 0 0]
[0 1 1 1 0 0 0 0 0 0]
